### ISSUE TITLE
Validation fails

### ISSUE THREAD

**Issue by adelina-t** [e2e-win/flannel-kubernetes#8]
TASK [linux/validation : Linux validation | Confirm K8s minions health] ********
fatal: [10.113.0.12]: FAILED! => {"msg": "'dict object' has no attribute 'kube-minions-linux'"}

Probably expects to have a minion linux node.

**Comment by papagalu** [comment]
it never fails for me( one k8s-master and one k8s-minion-windows)

how does your inventory/hosts file look like?

**Comment by adelina-t** [comment]
NOTE: The failure is probably induced by the way the runner generates the inventory/hosts file. Extra investigation is required.
